name: flachwitze
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/anti.txt
    - assets/chuck-norris.txt
    - assets/deine-mutter.txt
    - assets/gespraeche.txt
    - assets/namen.txt
    - assets/scherzfragen.txt
    - assets/sprueche.txt
    - assets/verabschiedungen.txt
    - assets/scherzfragen-nsfw.txt
    - assets/betrinken.txt
