name: flachwitze
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/anti.txt
    - assets/chuck-norris.txt
    - assets/deine-mutter.txt
    - assets/gespraeche.txt
    - assets/namen.txt
    - assets/scherzfragen.txt
    - assets/sprueche.txt
