name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter test
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /flachwitze/
